---
- project:
    vars:
      ensure_tox_version: '<4'
    check:
      jobs:
        - openstack-tox-linters
        - k8sapp-node-feature-discovery-tox-py39
        - k8sapp-node-feature-discovery-tox-pylint
        - k8sapp-node-feature-discovery-tox-flake8
        - k8sapp-node-feature-discovery-tox-metadata
    gate:
      jobs:
        - openstack-tox-linters
        - k8sapp-node-feature-discovery-tox-py39
        - k8sapp-node-feature-discovery-tox-pylint
        - k8sapp-node-feature-discovery-tox-flake8
        - k8sapp-node-feature-discovery-tox-metadata
    post:
      jobs:
        - stx-app-node-feature-discovery-upload-git-mirror

- job:
    name: k8sapp-node-feature-discovery-tox-py39
    parent: tox-py39
    description: |
        Run py39 for node-feature-discovery app
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-node-feature-discovery/*
    vars:
        tox_envlist: py39
        python_version: 3.9
        tox_extra_args: -c python3-k8sapp-node-feature-discovery/k8sapp_node_feature_discovery/tox.ini
        tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-node-feature-discovery-tox-metadata
    parent: tox
    description: |
        Run metadata test for node-feature-discovery app
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    vars:
        tox_envlist: metadata
        tox_extra_args: -c python3-k8sapp-node-feature-discovery/k8sapp_node_feature_discovery/tox.ini
        tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-node-feature-discovery-tox-pylint
    parent: tox
    description: |
        Run pylint test for node-feature-discovery app
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-node-feature-discovery/*
    vars:
        tox_envlist: pylint
        tox_extra_args: -c python3-k8sapp-node-feature-discovery/k8sapp_node_feature_discovery/tox.ini
        tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-node-feature-discovery-tox-flake8
    parent: tox
    description: |
        Run flake8 test for node-feature-discovery app
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-node-feature-discovery/*
    vars:
        tox_envlist: flake8
        tox_extra_args: -c python3-k8sapp-node-feature-discovery/k8sapp_node_feature_discovery/tox.ini
        tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: stx-app-node-feature-discovery-upload-git-mirror
    parent: upload-git-mirror
    description: >
      Mirrors opendev.org/starlingx/app-node-feature-discovery to
      github.com/starlingx/app-node-feature-discovery
    vars:
      git_mirror_repository: starlingx/app-node-feature-discovery
    secrets:
      - name: git_mirror_credentials
        secret: stx-app-node-feature-discovery-github-secret2
        pass-to-parent: true

- secret:
    name: stx-app-node-feature-discovery-github-secret2
    data:
      user: git
      host: github.com
      # yamllint disable-line rule:line-length
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
      ssh_key: !encrypted/pkcs1-oaep
        - SUmrvnH710n17VECqTDp6z1/PJoSIuCBNhx2HbydsfL1ggWyvfFurdZ+qnyEuVeR4UfO7
          VqrUlK4lCQa+wlacOw9OAtvkF4xfoQOD1OTWzt3CpQlCp1SufIUdkV3um6GwNt7IWtWOF
          4hiclfgtTWhBG1uStUxMrMoyDtFFIZ9X8XAKPoqMlTYdooAoA9Nzj1b7O8GEcA3jDEK5W
          7cYGHMlb5OhWRSLcoNd/gwL2SJz0bGYE3jcQbl0fqwvhreMYnMv0xCxTWOQMVpIKe7fl6
          JEFO/JqYpnHOd5tj3EQa+W5xA8bwn77uZyyFrOWsD/QegNoV4Gq1VKhBQQrpIi49w51xw
          /PFX+uN3BfI4Eg6qxidzKJcceX5b/rWihtePu8OyfEFNw3rYUaefbG3bpxAmzsxOh7R0j
          rxlqCYcKO3GW97dCJqKl3pwRnXgcUGdRNhyfCrTMKTAXTMLNxiozSrpOuMdaAh/8vAc+i
          +9d+tI6pwTSxgveZGWJBa1sguPR2YSH8vSto3e0Ni5Cl+PNbSSoQ/QBkxLg2/4TCnv0XE
          oPPbXyusKWQIfnp3RcfK+kaPsm/XuC8EnrbNXDSwP98x0+sY8NwHpl/e+X6XkB9WsfyHr
          AOVd2UDKHcCSXhmf1jppvYFyqkvKYymhfEhZW3tZ7udaQjBmD29/AEqlK1xiYs=
        - a3QcbYn6r9cARaA3YobGLXibWh5PdTeSTufGvBGVJEyerx3i61L0qgzus3Ewh0lOeBbur
          IR7L6H3j1cdf0LD+iy4Ejas3t+LpRLKXZkC7IHvVix59PaDm5FvcqUkaUvv8SWfcLn536
          +LYTnwob+a2lKOdVmPj7h4H5ysOf9ET7LHOW6Zj37IR9GbpaEdrraUJN2mXXbSA5KEqAh
          rXmJnTK6w/arak45tuqQ6ncvBejyJO/kQ4PzRBIIq5CWkwho7HqFEcSRFtQxn3mqGFHCL
          m6DWWodUcbF/vS4WA9H0Y0bCBCasXKM4t9AyGFplAV3YVgosgHktuydWyPvZ2Dq8gCtCY
          hyoB5dpuvA2yfBQaO0nqCxEVB5hB+ihrJ+7xzY+GJt3Iym+nE3cnp4CayqVF4QNq9rdV5
          CZY60cq1MRUAfvSSKdsAhnYFcHtSWD+J4KfHRi8CJOMqeav4Roam/LY/Y5hAHf/MEHHjA
          lbx7MmFN3hKtBPXTdgGWanRboGMh3vwvED8HqAThZ1VsuxUbO84DhP3LLiTLdTy2Xux7k
          wDxXnrqHvyahoczzEIK7N22xGmMY3Kn6g9yYI+5K8Tj3A70u+eU0XBGM08NP71d1tTMWp
          FRQ48qtFnZFiNY9stWA/Rg/eRFPoGLHCtl+/h3GugwATNFxlD1Q58HdOcy+0rY=
        - Nu9E5+LHBATyq8512+o3q1Qu2w41k9pOkYtrZtqBTvjayEVSooDhGpoW5AqjjkHfP6h2L
          iT2wrhFaVJnU0Dcg4fOkiPHlpkaGoteGYD+7aTCHeeCXAq87WMsg9rCFVxvCjKdLMpeu4
          ewRXVzmnqpcsUjV/AS/AoeMuE5zZSYCm7LS8KLjpG636x/YjZhEP2bIUayAgD4ut2xdyG
          5qAm/GCyT2KKbNBUa+nLeUMGYN+SgqUrm+Sq1XJql/9RZkVEvWe2VeFFHMXE63b1SepY0
          9pQenXz6iz9yfqQxgUa4HSvQBgKaJJsyWBPUneXrq7gVXtj3RT8yLVMOgsQbyNvKd2j1c
          /baXag+pHASng90R2CDDVSveBBUYjOuo7BvtahB4p26GdROnRkGADqAez+Zo9oO4w5NMA
          UlDnXfHV2EH8Ed3ZTNO2YCHHwibhdlEXNYtWWWg9w2m1NN4uP2TasZCbgiWa8y5x4MeL+
          F8ddLckqIrYQDRp1szvc+aqnWazfilp+jYxjMBcGWMUM3ambFaj8Iq1+LT1DqT005lNtV
          4AUPXnoI3LZHTcF4vrVqlwmJNosNVftdbGBZgju8JIGHJfPxu/H9P6cB+nGnsva7ahyOn
          tmUZm5zkqJwDh/xvudr9pzXKMIAWOTS8oaZtkZdqKKUFgboSx7uOY+0NsgBmsA=
        - FPPt43+AJLl6o8c3XDClkBc+/RSXLltT4BbWoP6zFibdyJHC66DUqJGFSJCHMCjAU0eb+
          Bh/TSi+hpf+YibS3BYv6h/AepTY2YWdxKhckoZW/BefWf+p1fIwwXQsa83t+vuNrx5iqR
          lepSNd1UYsZ3hL5yTRRuxJ199N0PUSNMWNbDBf1HVgBL8hxErLg/I8wK4Kj/2Fl9AR7Dd
          QSfYg7GMsypl9l4W9gwoSUMbyi7bqBSr1SO/mygElmyFGmLiKKj+csuz5e6FQHujgIV3q
          qSIIpyfJDO0pSOaMBwQZia7Fn/9BFPBa9bCM+2lQW9pucd1uXOh5ASpARerTTbtwDaooE
          ckxIZ77C7q2XrT+zTrwJfevXh3dc83tMNo8z+EBLl87ap9YGWgT+Xd4awnCgeKeS6Qeme
          dhDM/sxJtM6cL88yygyqqWLV13P1mup+TWlLIowegkZFzJevNqdMd/e53dFj6DSM5k7Lw
          QADmBv3CInq79vk/yQaWXQ8H6MbmZSSfD9quaVb/0GFAIBfWq1qH12djMhAiWmDElmAXd
          EUzRJ2f/mNO03Hxan2v6t3y1VgwU7p2a/yFuvWKPV0bwcJxr1BuYsNExgCHyTj6xS0Kt6
          uXBspRus4NP+0ec2zfF+Z1KcHJd8oqN9WvtcrIJJCaHHX7bq6T44H7tDSm4ng0=
        - SuMvQ0WX+AtgIn2BuWWZPhKdTG+4/IY+jIDgReXRU20C/a/lCqLAubhXuaZSbE1UPX0Ks
          Bo86Tkq69XJO/QHzOitAQHoJeuJG5a8+C6Bol+QGrgHJ3fYDROxNGWdHZf/gVehh00F0O
          DIl0dbH+U0q1jCea+bCwmU96TJQLlX1sdb6mLy1bGlEW7gPjyRQVbSnG0MpIYRQ8rMNkc
          BzEpDW7PJIdI9GEIteWjCip8cakq6tRNebRNkpEcwffJkZyYWeRReJQTvGyB1/5UA+f4L
          2S+gXCoA17/R8oGYtaApFslcn1egb9rwpK8VlCjpra0N/1uDnxt1OiodGhM9oZjYLuV+P
          /yoAwMm0Pss6E2b+smNSztd+2xtWAhBJZhsuxIQ5YWnRYAmH/aF7ptMBDfkRO4esYFp4B
          TAEIjCNIaDH2a2tRGz8QoFivuooLiAgu+nwQVktVq2HYa+/y5+6Syfw4s4nV+BZLt/ay4
          BXJlTULaJ5TVX/FjaWYvzc0rxBab0e0NgDNtGOafXMN4XZ26NfwYu8pkX4D4YHFSuh4Ql
          1oOzEkK8iSaVGekYwupH85R9lkBOvsSami+RtF73sllquz7O3mjME3bmnELE3C2vUamsL
          EyAYac1n8IWdTbRMx5AQEwV3JJzPug/JlO/bihLB/iNgXkxgTr2pleMH1fBc6Y=
        - ivWMey56PlHJ1VeKUC++j7wpRoUY4R+NxMIFbO202qH7Ng8y3IAN087dddY9vsyJ9G8qL
          CJ6qGcI04udnmPJnvW9nMdGm5rFPkMrPMADEziXXvkbT9S3QoRBFrwhKPPYBrit9EaArX
          1oe/5ZMrhcklfdPT8+wLi1t6LAQJwdAB1MEZH3UlNPEhoE4pcAZwMQL3/RTOv6cBGtyyD
          M7O5fAH3ELoTj2ERD5ljge0pY4Qt/h/LPt5Q4MBJS6MwcgUx/MIF+PY+Ks72OVeNgE47H
          T1nSCBkgqhnVjTvPKfTY/8jgCaBlTkK26bSR9XJ15/wRf6+blXBVJdTTuK9TertIL2zzG
          IPu/P/GlZL5srQqKSDGrEw6UCy58Ox+EzDwux1Bglz8m1HRFh5oqgyMq9DeT7swZQsTix
          B02/6sUnOMATcwoPadWjbLwZQWordXvJlLFTCNYxJ/s2Jlk+pTDvN9DiIa/E53GWQwNLj
          6oWHWAp8uaTz9hCMJHIwSGu/IrGkGLRAdiEoqRwBR7fhItcsPZTophe4oWhn3jXdK4+CY
          W2emvr1W2wF8PkSdS8PDg+DYNceksFAR3huGpvjAyj9EuA/tMd9fYZJceXh4jQHOcqE1K
          MgplZd91/k4kKEGtnhKq/gGRrCswUMcaDm54OQbHT72G+9pLrSCb6dsu721yqY=
        - bFE0xuFSBrP/yP21J6kHAo0z5oD2KGH7/8un1XVnSs68AnUcIrlqoKoITq4XcMN4Fc80J
          22bix+GrHgEhnornkZ9AW+GYmMNo9bneEPq5pCfjs1ux0N5pPkBOKj76KRIwLJS3p6kF1
          0+9ryHpDro+sH1QrqOSiu0yta9/I8vB1b0s41zdQlqrCAOHOGuqdoEh+YjXLREENx2W/E
          qpEUE6NZZyBrBg0X0RoA33jAyAQvd29GMNZ5WxVQtvSIXuRYvoGYbYvtm34J+wvOPeWJn
          Amv/QWbWo+0rgjVoxDt2ZGQhX3Ut2FqyoZSUEI3LTNZLjjKng7Z+kLZbuvNIT9NYhHXgP
          CcNAfa9VIHZitWl4T7sJpFiwlrXC+Qqj/D/xu9SbFVDwikmPNPUM2zxLUd/eZI1mbI+YZ
          ejsGH6X9pOUgP1mpRdaC4xjmPOzq5NrYw4ktxvx006IHxJy1my71PorPyCVOSXwPxvXxi
          QP1nbFcftF6vfEAUdn9yvNqoFYUmHUNm8VfByFCORQHPJw+Vl+l1ytaw/EINDT6ea944l
          ptqxvAeFkrL7AdQYt3avKjyiHUF/6RwosY/Fo42IAFe0C/vP12uTwt1tv6DU3sutcDikP
          CYQQKJ1+Mi3n9/zh6LaNnXEj9nn/oNk0VmQnnn8HsXBsXl3mevz8w335+Xb+uc=
