[metadata]
name = k8sapp-node-feature-discovery
summary = StarlingX sysinv extensions for node-feature-discovery
long_description = file: README.rst
long_description_content_type = text/x-rst
license = Apache 2.0
author = StarlingX
author-email = starlingx-discuss@lists.starlingx.io
home-page = https://www.starlingx.io/
classifier =
    Environment :: OpenStack
    Intended Audience :: Information Technology
    Intended Audience :: System Administrators
    License :: OSI Approved :: Apache Software License
    Operating System :: POSIX :: Linux
    Programming Language :: Python
    Programming Language :: Python :: 2
    Programming Language :: Python :: 2.7
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.4
    Programming Language :: Python :: 3.5
    Programming Language :: Python :: 3.9

[files]
packages =
    k8sapp_node_feature_discovery

[global]
setup-hooks =
    pbr.hooks.setup_hook

[entry_points]
systemconfig.helm_applications =
    node-feature-discovery = systemconfig.helm_plugins.node_feature_discovery

systemconfig.helm_plugins.node_feature_discovery =
    001_node-feature-discovery = k8sapp_node_feature_discovery.helm.node_feature_discovery:NodeFeatureDiscoveryHelm

systemconfig.app_lifecycle =
    node-feature-discovery = k8sapp_node_feature_discovery.lifecycle.lifecycle_node_feature_discovery:NodeFeatureDiscoveryAppLifecycleOperator

[bdist_wheel]
universal = 1
